import { fireEvent, render } from '@testing-library/svelte';
import { afterAll, beforeAll, describe, expect, it, vi } from 'vitest';
import PieChart from './PieChart.svelte';

const data = Array.from({ length: 7 }, (_, index) => ({
  label: `Item ${index}`,
  value: index + 1
}));
const props = { data, showLegend: true, legendShowValues: true, legendMaxItems: 5 };

// jsdom cannot observe layout; these tests exercise the legend's DOM state,
// not ChartContainer's separately browser-tested measurement.
beforeAll(() => {
  vi.stubGlobal(
    'ResizeObserver',
    class {
      observe() {}
      unobserve() {}
      disconnect() {}
    }
  );
});
afterAll(() => vi.unstubAllGlobals());

describe('PieChart legend bounds', () => {
  it('uses an integer cap for rows and the hidden count', () => {
    const { container, getByRole } = render(PieChart, { ...props, legendMaxItems: 5.7 });
    expect(container.querySelectorAll('.pie-legend-row')).toHaveLength(5);
    expect(getByRole('button').textContent?.trim()).toBe('+2 more');
  });

  it('resets expansion when the data length changes', async () => {
    const { container, getByRole, rerender } = render(PieChart, props);
    await fireEvent.click(getByRole('button'));
    expect(container.querySelectorAll('.pie-legend-row')).toHaveLength(7);
    await rerender({ ...props, data: data.slice(0, 3) });
    await rerender(props);
    expect(container.querySelectorAll('.pie-legend-row')).toHaveLength(5);
  });

  it.each([0, -1, Number.NaN, Number.POSITIVE_INFINITY])('ignores invalid cap %s', (cap) => {
    const { container, queryByRole } = render(PieChart, { ...props, legendMaxItems: cap });
    expect(container.querySelectorAll('.pie-legend-row')).toHaveLength(7);
    expect(queryByRole('button')).toBeNull();
  });

  it.each([7, 8])('does not render an expander when cap %s covers all rows', (cap) => {
    const { container, queryByRole } = render(PieChart, { ...props, legendMaxItems: cap });
    expect(container.querySelectorAll('.pie-legend-row')).toHaveLength(7);
    expect(queryByRole('button')).toBeNull();
  });

  it('clamps a positive sub-unit cap to one row', () => {
    const { container, getByRole } = render(PieChart, { ...props, legendMaxItems: 0.5 });
    expect(container.querySelectorAll('.pie-legend-row')).toHaveLength(1);
    expect(getByRole('button').textContent?.trim()).toBe('+6 more');
  });

  it('has no rows or expander for empty data', () => {
    const { container, queryByRole } = render(PieChart, { ...props, data: [] });
    expect(container.querySelectorAll('.pie-legend-row')).toHaveLength(0);
    expect(queryByRole('button')).toBeNull();
  });

  it('collapses when the cap changes after expansion', async () => {
    const { container, getByRole, rerender } = render(PieChart, props);
    await fireEvent.click(getByRole('button'));
    await rerender({ ...props, legendMaxItems: 3 });
    expect(container.querySelectorAll('.pie-legend-row')).toHaveLength(3);
    expect(getByRole('button').getAttribute('aria-expanded')).toBe('false');
  });

  it('collapses when same-length data is replaced with different rows', async () => {
    // The row count is identical across this swap, so the collapse can only
    // come from tracking the prop itself -- a reset that compared counts would
    // leave the new list stuck open on the previous list's expansion.
    const swapped = data.map((row) => ({ ...row, label: `Other ${row.label}` }));
    const { container, getByRole, rerender } = render(PieChart, props);
    await fireEvent.click(getByRole('button'));
    expect(container.querySelectorAll('.pie-legend-row')).toHaveLength(7);

    await rerender({ ...props, data: swapped });
    expect(container.querySelectorAll('.pie-legend-row')).toHaveLength(5);
    expect(getByRole('button').getAttribute('aria-expanded')).toBe('false');
  });

  it('always gives the expander a non-empty accessible name', () => {
    // The label is generated by the component -- there is no prop that could
    // make it blank -- so this pins that it stays that way.
    const { getByRole } = render(PieChart, props);
    expect(getByRole('button').textContent?.trim()).toBe('+2 more');
  });

  it('points the built-in expander at the list it expands', () => {
    const { container, getByRole } = render(PieChart, props);
    const list = container.querySelector('.pie-legend-values');
    expect(getByRole('button').getAttribute('aria-controls')).toBe(list?.id);
    expect(list?.id).toBeTruthy();
  });

  it('keeps the empty state out of the beside-chart row layout', () => {
    // A flex row with no legend rows turns the empty message into a flex item
    // instead of the full-width block the docs describe.
    const { container } = render(PieChart, { ...props, data: [], legendPosition: 'right' });
    expect(container.querySelector('.pie-chart.legend-right')).toBeNull();
  });

  it('does not claim to control expansion in callback mode', async () => {
    let calls = 0;
    const { container, getByRole } = render(PieChart, {
      ...props,
      onlegendmore: () => {
        calls += 1;
      }
    });
    const button = getByRole('button');
    expect(button.hasAttribute('aria-expanded')).toBe(false);
    expect(button.hasAttribute('aria-haspopup')).toBe(false);
    await fireEvent.click(button);
    expect(calls).toBe(1);
    expect(container.querySelectorAll('.pie-legend-row')).toHaveLength(5);
  });
});
