import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { parseArgs } from 'node:util';
import { pathToFileURL } from 'node:url';

/**
 * Generates a compatibility stylesheet for the `:host` display change landed in this PR.
 *
 * Every `src/wc/components/*.svelte` wrapper now declares
 * `:host { display: var(--sui-<name>-display, <block|inline-block>) }`. Before this PR none of
 * them had a `:host` rule at all, so the browser's implicit `display: inline` for an unknown
 * element applied. A consumer who laid out around that now gets different layout at an
 * unchanged call site — regardless of whether the new default is `block` or `inline-block`,
 * both differ from the old implicit `inline`.
 *
 * The fix is one custom-property override per element, always pinned to the literal `inline`
 * that used to apply implicitly:
 *
 *   sui-badge { --sui-badge-display: inline; }
 *
 * Both the tag and the custom-property name are read off each wrapper's own
 * `svelte:options`/`:host` declaration (never assembled from a naming convention), so the
 * generated file cannot drift from the source the way a hardcoded list would.
 */

export type HostDisplayEntry = {
  readonly file: string;
  readonly tag: string;
  readonly property: string;
  readonly newDefault: string;
};

export type CollectResult = {
  readonly entries: readonly HostDisplayEntry[];
  readonly skipped: readonly string[];
};

/** The one `tag: '…'` field inside a wrapper's `customElement={{ … }}` block. */
const TAG_PATTERN = /tag:\s*'([^']+)'/;

/**
 * The wrapper's own `:host` rule: `display: var(--sui-<name>-display, <default>)`.
 *
 * Captures the custom-property name verbatim (group 1) rather than reconstructing it from the
 * tag, so a future wrapper whose property name does not follow the `--sui-<tag>-display`
 * convention is still read correctly instead of silently mismatched. `\s*` already spans
 * newlines without a `dotAll`/`m` flag, so the comment block every wrapper has immediately
 * above its `:host` rule does not need to be skipped explicitly.
 */
const HOST_DISPLAY_PATTERN = /:host\s*\{\s*display:\s*var\((--[\w-]+)\s*,\s*([\w-]+)\)\s*;?\s*\}/;

/**
 * Reads one wrapper's tag and display custom-property + default straight off its source.
 *
 * Returns null — never a guess — when either half is missing, so a wrapper that lost its
 * `:host` rule (or never had a readable tag) is surfaced as a skip by the caller instead of
 * silently disappearing from the generated shim. A shim that is missing an entry looks exactly
 * as complete as one that is not, which is the worse failure mode here.
 */
export function parseHostDisplay(source: string, file: string): HostDisplayEntry | null {
  const tagMatch = TAG_PATTERN.exec(source);
  const hostMatch = HOST_DISPLAY_PATTERN.exec(source);
  if (tagMatch === null || hostMatch === null) {
    return null;
  }
  return {
    file,
    tag: tagMatch[1],
    property: hostMatch[1],
    newDefault: hostMatch[2]
  };
}

/** Reads every `.svelte` wrapper in `componentsDir`, keeping unreadable ones as `skipped`. */
export function collectHostDisplayEntries(componentsDir: string): CollectResult {
  const entries: HostDisplayEntry[] = [];
  const skipped: string[] = [];

  const files = readdirSync(componentsDir)
    .filter((name) => name.endsWith('.svelte'))
    .sort();

  for (const file of files) {
    const source = readFileSync(join(componentsDir, file), 'utf8');
    const parsed = parseHostDisplay(source, file);
    if (parsed === null) {
      skipped.push(file);
      continue;
    }
    entries.push(parsed);
  }

  return { entries, skipped };
}

const HEADER = `/**
 * COMPATIBILITY SHIM -- generated by scripts/migrate/host-display-compat.ts
 * Regenerate: node scripts/migrate/host-display-compat.ts --out <path>
 *
 * Before this version, none of these custom elements declared a :host display rule, so an
 * unknown element's browser default -- display: inline -- applied. This version gives each one
 * an explicit ":host { display: var(--sui-<name>-display, <default>) }", which is a real layout
 * change at an unchanged call site for any consumer who laid out around the old implicit inline.
 *
 * Each rule below pins that element's display custom property back to inline, restoring the
 * exact pre-upgrade layout: drop this file in, confirm nothing moved, then delete rules
 * one at a time as each call site is verified against the new default.
 *
 * DO NOT KEEP THIS FILE. Restoring the old implicit inline forever reintroduces the bug the
 * :host rule fixed: a percentage-width child of an implicitly-inline host has no width to
 * resolve against, so "width: 100%" inside one of these elements silently collapses. This
 * stylesheet is a crutch for the migration window, not a permanent override.
 */`;

function section(title: string, entries: readonly HostDisplayEntry[]): string {
  const rules = entries.map((entry) => `${entry.tag} { ${entry.property}: inline; }`).join('\n');
  return `/* ${title} (${entries.length}) */\n${rules}`;
}

/**
 * Every rule is pinned to the literal `inline` that used to apply implicitly, regardless of
 * whether the element's new default is `block` or `inline-block` — both are a change from the
 * old behaviour this shim restores. Entries are grouped by their new default (derived from what
 * was actually read, not a hardcoded 87/11 split) purely for a reader scanning the file; the
 * value written is uniform.
 */
export function generateStylesheet(entries: readonly HostDisplayEntry[]): string {
  const byDefault = new Map<string, HostDisplayEntry[]>();
  for (const entry of entries) {
    const group = byDefault.get(entry.newDefault) ?? [];
    group.push(entry);
    byDefault.set(entry.newDefault, group);
  }

  const sections = [...byDefault.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([newDefault, group]) =>
      section(
        `components whose new default is \`${newDefault}\``,
        [...group].sort((a, b) => a.tag.localeCompare(b.tag))
      )
    );

  return `${HEADER}\n\n${sections.join('\n\n')}\n`;
}

const USAGE = [
  'Usage: node scripts/migrate/host-display-compat.ts [--root <repo>] [--out <path>]',
  '',
  "Generates a compatibility stylesheet for this PR's :host display change: one rule per",
  '`src/wc/components/*.svelte` wrapper, pinning its --sui-<name>-display custom property back',
  'to the `inline` that applied implicitly before the wrapper declared a :host rule at all.',
  '',
  '  --root <repo>  repo to read src/wc/components from (default: cwd)',
  '  --out <path>   write the stylesheet here instead of printing it',
  '  --help         show this help',
  '',
  'Prints to stdout by default. Nothing is written without --out.'
].join('\n');

export type HostDisplayCompatSummary = {
  readonly exitCode: number;
  readonly entryCount: number;
  readonly skipped: readonly string[];
  readonly outPath: string | null;
};

export function run(
  argv: readonly string[],
  log: (line: string) => void
): HostDisplayCompatSummary {
  let parsed;
  try {
    parsed = parseArgs({
      args: [...argv],
      options: {
        root: { type: 'string', default: '.' },
        out: { type: 'string' },
        help: { type: 'boolean', default: false }
      },
      allowPositionals: false
    });
  } catch (error) {
    log(error instanceof Error ? error.message : String(error));
    log(USAGE);
    return { exitCode: 2, entryCount: 0, skipped: [], outPath: null };
  }

  if (parsed.values.help === true) {
    log(USAGE);
    return { exitCode: 0, entryCount: 0, skipped: [], outPath: null };
  }

  const rootFlag = parsed.values.root;
  const root = resolve(typeof rootFlag === 'string' ? rootFlag : '.');
  const componentsDir = join(root, 'src/wc/components');

  if (!existsSync(componentsDir)) {
    log(`error: ${componentsDir} does not exist`);
    return { exitCode: 2, entryCount: 0, skipped: [], outPath: null };
  }

  const { entries, skipped } = collectHostDisplayEntries(componentsDir);

  for (const file of skipped) {
    log(`NOTE ${file}: no readable tag + :host display declaration -- skipped rather than guessed`);
  }

  if (entries.length === 0) {
    log('error: found no wc wrapper with a :host display declaration; nothing to generate');
    return { exitCode: 1, entryCount: 0, skipped, outPath: null };
  }

  if (skipped.length > 0) {
    // A stylesheet missing entries looks exactly as complete as one that is not -- refusing
    // outright beats shipping partial coverage that nobody asked to review as partial.
    log('');
    log(
      `refusing to generate: ${skipped.length} wrapper(s) above could not be read, and a shim ` +
        'silently missing them would leave those consumers unprotected without saying so'
    );
    return { exitCode: 1, entryCount: entries.length, skipped, outPath: null };
  }

  const stylesheet = generateStylesheet(entries);

  const outFlag = parsed.values.out;
  if (typeof outFlag === 'string' && outFlag.length > 0) {
    const outPath = resolve(outFlag);
    writeFileSync(outPath, stylesheet);
    log(`wrote ${entries.length} rule(s) to ${outPath}`);
    return { exitCode: 0, entryCount: entries.length, skipped, outPath };
  }

  for (const line of stylesheet.split('\n')) {
    log(line);
  }
  return { exitCode: 0, entryCount: entries.length, skipped, outPath: null };
}

// Comparing against a basename split on '/' fails on Windows, where argv[1] uses backslashes
// and the split yields the whole path -- the CLI then silently declines to run. Normalising
// both sides to a file URL is platform-agnostic. (Same guard as scripts/migrate/cli.ts.)
const entrypoint = process.argv[1];
const invokedDirectly =
  typeof entrypoint === 'string' && import.meta.url === pathToFileURL(resolve(entrypoint)).href;

if (invokedDirectly) {
  const summary = run(process.argv.slice(2), (line) => console.log(line));
  process.exitCode = summary.exitCode;
}
